#!/bin/bash

# Download and install Elasticsearch
# Check http://www.elasticsearch.org/download/ for latest version of Elasticsearch and replace wget link
# Only download the file if it doesn't already exist
if [ ! -f elasticsearch-6.0.0.deb ]; then
    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
fi
# Install deb
sudo dpkg -i elasticsearch-6.0.0.deb

# Set JAVA_HOME (in case it is not automatically set)
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

# Enable on bootup
sudo systemctl enable elasticsearch.service
 
# Start ElasticSearch 
#sudo /etc/init.d/elasticsearch start

# Ask user for path to store data
_repeatPath="Y"
while [ $_repeatPath = "Y" ]
do
	echo -n "Enter path to data directory, separate multiple locations by comma (leave blank for default): "
read DPATH
# If empty, then set the default path
if [ -z "$DPATH" ]; then
    sudo sed -i 's|^path.data: .*$|path.data: /var/lib/elasticsearch|' /etc/elasticsearch/elasticsearch.yml
    echo "Set to the default path"
    _repeatPath="N"
# Else, check if the path exists; if it doesn't ask again
elif [ ! -e "$DPATH" ]; then
    echo "Invalid path"
else
    # Give permissions to elasticsearch (this is the default user running the application)
    setfacl -m u:elasticsearch:rwx $DPATH
    # Replace the old path with the given one
    sudo sed -i 's|^path.data: .*$|path.data: '"$DPATH"'|' /etc/elasticsearch/elasticsearch.yml 
    _repeatPath="N"
fi
done

# Ask user to set IP
_repeatIP="Y"
while [ $_repeatIP = "Y" ]
do
	echo -n "Enter IP address: "
read IP
# If empty
if [ -z "$IP" ]; then
    : # Do nothing
else
    # Replace IP
    sudo sed -i 's|^[#]*network.host: .*$|network.host: '"$IP"'|' /etc/elasticsearch/elasticsearch.yml
    _repeatIP="N"
fi
done

# Ask user to set port
_repeatPort="Y"
while [ $_repeatPort = "Y" ]
do
	echo -n "Enter port number: "
read PORT
# If empty
if [ -z "$PORT" ]; then
    : # Do nothing
else
    # Replace port
    sudo sed -i 's|^[#]*http.port: .*$|http.port: '"$PORT"'|' /etc/elasticsearch/elasticsearch.yml 
    _repeatPort="N"
fi
done

# Ask user to set amount of RAM
echo "RAM setting. Do not set more than 50% of available RAM. Do not exceed 32 GB. Less than 8 GB tends to be counterproductive."
echo -n "Enter RAM amount in GB: "
read RAM
sudo sed -i 's|^-Xms.*$|-Xms'"$RAM"'g|' /etc/elasticsearch/jvm.options
sudo sed -i 's|^-Xmx.*$|-Xms'"$RAM"'g|' /etc/elasticsearch/jvm.options

# Start ElasticSearch 
sudo /etc/init.d/elasticsearch start
echo "Starting service..."
sleep 10
echo "Setting parameters. Please wait..."
sleep 10
echo "Sending request..."

# Check if elasticsearch service is running
curl --connect-timeout 30 http://$IP:$PORT

# Should return something like this:
# {
#  "status" : 200,
#  "name" : "Storm",
#  "version" : {
#    "number" : "1.3.1",
#    "build_hash" : "2de6dc5268c32fb49b205233c138d93aaf772015",
#    "build_timestamp" : "2014-07-28T14:45:15Z",
#    "build_snapshot" : false,
#    "lucene_version" : "4.9"
#  },
#  "tagline" : "You Know, for Search"
#}
